.PHONY: clean All

All:
	@echo "----------Building project:[ 20-IfElse - Debug ]----------"
	@cd "20-IfElse" && "$(MAKE)" -f  "20-IfElse.mk"
clean:
	@echo "----------Cleaning project:[ 20-IfElse - Debug ]----------"
	@cd "20-IfElse" && "$(MAKE)" -f  "20-IfElse.mk" clean
