.PHONY: clean All

All:
	@echo "----------Building project:[ 04-Variables - Debug ]----------"
	@cd "04-Variables" && "$(MAKE)" -f  "04-Variables.mk"
clean:
	@echo "----------Cleaning project:[ 04-Variables - Debug ]----------"
	@cd "04-Variables" && "$(MAKE)" -f  "04-Variables.mk" clean
