.PHONY: clean All

All:
	@echo "----------Building project:[ 22-Switch-case-with-Enums - Debug ]----------"
	@cd "22-Switch-case-with-Enums" && "$(MAKE)" -f  "22-Switch-case-with-Enums.mk"
clean:
	@echo "----------Cleaning project:[ 22-Switch-case-with-Enums - Debug ]----------"
	@cd "22-Switch-case-with-Enums" && "$(MAKE)" -f  "22-Switch-case-with-Enums.mk" clean
